# While Loop

In [4]:
i=0 ###
while i<=5:
    print(i)
    i=i+1
else:
    print("out of while loop")

0
1
2
3
4
5
out of while loop


In [8]:
i=0
b=5
while i<=b:
    print("i","b",i,b)
    i=i+1
else:
    print("Out while loop as a is greater than b")


i b 0 5
i b 1 5
i b 2 5
i b 3 5
i b 4 5
i b 5 5
Out while loop as a is greater than b


In [9]:
marks=90
if marks>=90:

    print('excellent')
elif marks>=50 and marks < 90:
    print('Average')
else:
    print('poor')

excellent


# For Loop

In [13]:
lst=[1,2,3,4,5,6,7,8,9,10]
for i in lst:
    a=i*4
    print(i,a)

1 4
2 8
3 12
4 16
5 20
6 24
7 28
8 32
9 36
10 40


In [37]:
lst=[1,2,3,4,5,6,7,8,9,10]
[i*4 for i in lst if i <4]

[4, 8, 12]

In [14]:
import numpy as np

In [16]:
np.random.randint(0,37)

32

In [20]:
lst=[1,2,3,4,5]
lst_1=[6,7,8,9,10]
for i in lst:

    for j in lst_1:
        print(i,j)

1 6
1 7
1 8
1 9
1 10
2 6
2 7
2 8
2 9
2 10
3 6
3 7
3 8
3 9
3 10
4 6
4 7
4 8
4 9
4 10
5 6
5 7
5 8
5 9
5 10


In [21]:
clothes = ["shirt", "sock", "pants", "socks", "towel"]
paired_socks = []
for item in clothes:
    if item == "sock":
        a=item
        continue
        
    else:
        print(f"in else statement {item} ")
paired_socks.append(a)
print(paired_socks)


in else statement shirt 
in else statement pants 
in else statement socks 
in else statement towel 
['sock']


In [25]:
list(range(0,20))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [26]:
list(range(0,20,2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [27]:
l=[100,101,102,103]
l1=[1,2,3,4]
z=zip(l,l1)
for (x,y) in z:
    s=x+y
    print(s)


101
103
105
107


In [28]:
l1 = ["eat", "sleep", "repeat"]
for ele in enumerate(l1):
    print (ele)


(0, 'eat')
(1, 'sleep')
(2, 'repeat')


# List Comprehension

In [38]:
lst=[1,2,3,4,5,6,7,8,9,10]
[i*4 for i in lst]

[4, 8, 12, 16, 20, 24, 28, 32, 36, 40]

In [39]:
lst=[1,2,3,4,5,6,7,8,9,10]
[i*4 for i in lst if i <4]

[4, 8, 12]

In [43]:
lst2=range(0,10)

In [44]:
[i*4 for i in lst2]

[0, 4, 8, 12, 16, 20, 24, 28, 32, 36]

In [48]:
[i*5 for i in range(0,10,2)]

[0, 10, 20, 30, 40]

# Functions

In [53]:
def Greet (name):
    name=("Hello", name)
    
    return name


In [54]:
Greet("Sunit")

('Hello', 'Sunit')

In [55]:
x=100
def multi(y):
    z=x*y
    print(z)

    
multi(5)


500


In [57]:
def accuracy(a,b,c,d):
    
    x=a+b+c+d
    y=d-c-b-a
    return x,y

In [58]:
accuracy(1,2,3,4)

(10, -2)

In [60]:
y

4

In [61]:
lst=[10,20,30,40,50]
one_d_array=np.array(lst)

In [62]:
print(one_d_array)

[10 20 30 40 50]


In [63]:
type(one_d_array)

numpy.ndarray

In [64]:
type(lst)

list

In [65]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
np.ones((4,3),dtype="int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [97]:
np.zeros(12).reshape(6,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [71]:
np.empty((3,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [75]:
multidimension=np.array([[10,20,30],[20,30,40]])
print(multidimension)

[[10 20 30]
 [20 30 40]]


In [73]:
multidimension.ndim ###dimension

2

In [74]:
multidimension.shape

(2, 3)

In [76]:
multidimension.size

6

In [78]:
multidimension.dtype

dtype('int64')

In [79]:
multidimension.nbytes

48

In [92]:
np.arange(111,1113,10)

array([ 111,  121,  131,  141,  151,  161,  171,  181,  191,  201,  211,
        221,  231,  241,  251,  261,  271,  281,  291,  301,  311,  321,
        331,  341,  351,  361,  371,  381,  391,  401,  411,  421,  431,
        441,  451,  461,  471,  481,  491,  501,  511,  521,  531,  541,
        551,  561,  571,  581,  591,  601,  611,  621,  631,  641,  651,
        661,  671,  681,  691,  701,  711,  721,  731,  741,  751,  761,
        771,  781,  791,  801,  811,  821,  831,  841,  851,  861,  871,
        881,  891,  901,  911,  921,  931,  941,  951,  961,  971,  981,
        991, 1001, 1011, 1021, 1031, 1041, 1051, 1061, 1071, 1081, 1091,
       1101, 1111])

In [93]:
np.linspace(11,1113,10)

array([  11.        ,  133.44444444,  255.88888889,  378.33333333,
        500.77777778,  623.22222222,  745.66666667,  868.11111111,
        990.55555556, 1113.        ])

In [111]:
rng=np.random.default_rng(42)


In [106]:
rng.random(10) 


array([0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394,
       0.33966929, 0.062511  , 0.35706816, 0.20250319, 0.4305179 ])

In [112]:
rng.integers(0, 100,10)


array([ 8, 77, 65, 43, 43, 85,  8, 69, 20,  9])

In [107]:
rng.normal(10,5,7)


array([17.86374339,  7.26107561,  8.54153216, 13.60574701,  9.20798481,
        8.8109699 , 12.48272073])

In [8]:
a=np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
  [10,11,12]
   ])

b=np.array([3, 4, 8])
c=np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
  [10,11,12]
   ])
d=a*b
e=a*c


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# IF ELSE STATEMENT
# WHILE LOOP
# FOR LOOP 
# LIST COMPREHENSION
# ANY ONE FUCNTION 
# ALL PYTHON BUILT IN DATA TYPES 

In [16]:
import numpy as np

In [26]:
rng=np.random.default_rng(42)


In [29]:
array_2d=rng.integers(11,23,10).reshape(5,2)


In [32]:
array_1d=rng.integers(11,23,10)

In [33]:
print(array_2d)

[[17 15]
 [13 22]
 [20 18]
 [15 20]
 [17 16]]


In [34]:
print(array_1d)

[20 19 15 11 22 16 21 19 20 20]


In [48]:
product_list=['fruit','vegetable','cereal','dairy',"eggs","snacks","beverage","coffee","tea","spices"]

In [49]:
product_array=np.array(products)

In [46]:
product_array[1]

'vegetable'

In [51]:
product_list[1]

'vegetable'

In [52]:
product_list[5:]

['snacks', 'beverage', 'coffee', 'tea', 'spices']

In [54]:
product_array[5:]

array(['snacks', 'beverage', 'coffee', 'tea', 'spices'], dtype='<U9')

In [55]:
new_2darray=np.arange(11,23).reshape(3,4)


In [56]:
new_2darray

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [59]:
new_2darray[0:,0:1]

array([[11],
       [15],
       [19]])

In [65]:
new_2darray[0:1,0:2]

array([[11, 12]])

In [64]:
new_2darray[0:3,0:2]

array([[11, 12],
       [15, 16],
       [19, 20]])

In [66]:
new_2darray[1,1]

16

In [148]:
rng=np.random.default_rng(42)
inventory=rng.integers(0,100,10)

In [90]:
price=(rng.random(10)*10).round(2)
new_price=(rng.random(11)*10).round(2)

In [84]:
inventory

array([ 8, 77, 65, 43, 43, 85,  8, 69, 20,  9])

In [89]:
inventory*10*price

array([ 181.6, 4273.5,  416. , 3560.4, 2717.6, 6443. ,  284. , 6699.9,
       1786. ,  700.2])

In [149]:
inventory*10

array([ 80, 770, 650, 430, 430, 850,  80, 690, 200,  90])

In [92]:
new_price

array([1.89, 1.3 , 4.76, 2.27, 6.7 , 4.37, 8.33, 7.  , 3.12, 8.32, 8.05])

In [93]:
price

array([1.95, 4.67, 0.44, 1.54, 6.83, 7.45, 9.68, 3.26, 3.7 , 4.7 ])

In [153]:
a=np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
  [10,11,12]
   ])

b=np.array([3, 4, 8])
c=np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9],
  [10,11,12]
   ])
d=a*b
e=a*c


In [152]:
d

array([[ 3,  8, 24],
       [12, 20, 48],
       [21, 32, 72],
       [30, 44, 96]])

In [154]:
e

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [96]:
np_array=np.arange(20)
print(np_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [95]:
np_array[np_array%2==0]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [97]:
x=rng.integers(0,100,10)


In [98]:
x

array([84, 38, 89, 28, 23, 68, 63, 13, 83, 19])

In [100]:
x[(x>23) & (x<89)]

array([84, 38, 28, 68, 63, 83])

In [102]:
inventory=[12,102,18,0,0]
product=['fruit','vegetable','cereal'
              ,'dairy','eggs']
inventory_array=np.array(inventory)
product_array=np.array(product)



In [104]:
inventory_array

array([ 12, 102,  18,   0,   0])

In [105]:
product_array

array(['fruit', 'vegetable', 'cereal', 'dairy', 'eggs'], dtype='<U9')

In [103]:
product_array[inventory_array>0]

array(['fruit', 'vegetable', 'cereal'], dtype='<U9')

In [111]:
np.where(inventory_array<=0,"Out of Stock", "In Stock")

array(['In Stock', 'In Stock', 'In Stock', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [113]:
inventory_array

array([ 12, 102,  18,   0,   0])

In [114]:
product_array

array(['fruit', 'vegetable', 'cereal', 'dairy', 'eggs'], dtype='<U9')

In [115]:
np.where(inventory_array<=0,"Out of Stock",np.where(inventory_array>=102, "too many stock", "perfectly stock"))

array(['perfectly stock', 'too many stock', 'perfectly stock',
       'Out of Stock', 'Out of Stock'], dtype='<U15')

In [116]:
sales_array=rng.integers(0,100,10).reshape(2,5)


In [120]:
sales_array

array([[80,  0, 79, 78, 78],
       [66, 47, 70, 27, 78]])

In [125]:
sales_array.sum()

603

In [121]:
sales_array.mean()

60.3

In [122]:
sales_array.max()

80

In [123]:
sales_array.min()

0

In [133]:
sales_array=rng.integers(0,100,10).reshape(2,5)

In [127]:
sales_array.sum(axis=1)

array([315, 288])

In [128]:
sales_array.sum(axis=0)

array([146,  47, 149, 105, 156])

In [129]:
sales_array

array([[80,  0, 79, 78, 78],
       [66, 47, 70, 27, 78]])

In [131]:
sales_array.min(axis=1)

array([ 0, 27])

In [132]:
sales_array.min(axis=0)

array([66,  0, 70, 27, 78])

In [134]:
np.sqrt(sales_array)

array([[7.41619849, 6.70820393, 7.07106781, 7.48331477, 1.73205081],
       [3.60555128, 4.89897949, 3.31662479, 6.55743852, 8.1240384 ]])

In [135]:
np.mean(sales_array)

36.6

In [136]:
sales_array

array([[55, 45, 50, 56,  3],
       [13, 24, 11, 43, 66]])

In [137]:
sales_array.sort()

In [138]:
sales_array

array([[ 3, 45, 50, 55, 56],
       [11, 13, 24, 43, 66]])

In [141]:
sales_array.sort(axis=0)

In [140]:
sales_array

array([[ 3, 45, 50, 55, 56],
       [11, 13, 24, 43, 66]])

In [142]:
sales_array

array([[ 3, 13, 24, 43, 56],
       [11, 45, 50, 55, 66]])

In [145]:
lst=[1,2,3,4]
S=np.array([1,2,3,4])
S[0:2]=99
#S[3]=99


In [146]:
S

array([99, 99,  3,  4])